name: Add joke to pull request

on:
  pull_request:
    branches: [ "*" ]

jobs:
  add_joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create feature directory
        run: mkdir -p $GITHUB_WORKSPACE/feature

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Fetch all branches
        run: git fetch origin '+refs/heads/*:refs/remotes/origin/*'
        
      - name: Get Joke from API
        id: get_joke
        run: |
          raw_output=$(curl -s 'https://api.chucknorris.io/jokes/random')
          joke=$(echo "$raw_output" | jq -r '.value')
          echo "::set-output name=joke::$joke"
      
      - name: Add Joke to Pull Request
        run: |
          echo "## Joke of the Day" >> $GITHUB_WORKSPACE/feature/createJokeWorkflow.md
          echo "${{ steps.get_joke.outputs.joke }}" >> $GITHUB_WORKSPACE/feature/createJokeWorkflow.md
      
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Ensure you are on the branch of the pull request
          git checkout ${{ github.event.pull_request.head.ref }}
          
          # Stage and commit changes
          git add $GITHUB_WORKSPACE/feature/createJokeWorkflow.md
          git commit -m "Add joke to Pull Request"
          
          # Push changes to the pull request branch
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
