name: Add joke to pull request

on:
  pull_request:
    branches: [ "*" ]

jobs:
  add_joke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Create feature directory
        run: mkdir -p $GITHUB_WORKSPACE/feature

      - name: Get Joke from API
        id: get_joke
        run: echo "::set-output name=joke::$(curl -s 'https://api.chucknorris.io/jokes/random')"

      - name: Add Joke to Pull Request
        run: |
          echo "## Joke of the Day" >> $GITHUB_WORKSPACE/feature/createJokeWorkflow.md
          joke="${{ steps.get_joke.outputs.joke }}"
          escaped_joke=$(echo "$joke" | sed 's/\"/\\\"/g')
          echo "$escaped_joke" >> $GITHUB_WORKSPACE/feature/createJokeWorkflow.md
        
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.event.pull_request.head.ref }}
          git add $GITHUB_WORKSPACE/feature/createJokeWorkflow.md
          git commit -m "Add joke to Pull Request"
          git push origin ${{ github.event.pull_request.head.ref }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
